version: "3"
services:
    proxy:
        image: jwilder/nginx-proxy:latest
        container_name: proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - reverse-proxy
        restart: always

networks:
    reverse-proxy:
        driver: bridge
