version: "3"
services:
    hive_wallet:
        build: .
        image: hive/wallet:latest
        container_name: wallet
        ports:
            - 80:8080
            - 8080:8080
        environment:
            SDC_CLIENT_HIVED_URL: https://anyx.io
            SDC_SERVER_HIVED_URL: https://anyx.io
            SDC_DISABLE_SIGNUPS: 1

            # add to your /etc/hosts
            # 127.0.0.1     hiveblog.local
            SDC_SITE_DOMAIN: hiveblog.local

            SDC_IMAGE_PROXY_PREFIX: https://images.hive.blog/
            SDC_UPLOAD_IMAGE_URL: https://images.hive.blog
            SDC_HELMET_CONNECTSRC: "'self' http://hiveblog.local https://api.hive.blog  https://anyx.io https://images.hive.blog"
        volumes:
            - ./yarn.lock:/var/app/yarn.lock
            - ./package.json:/var/app/package.json
            - ./dev-start.sh:/var/app/dev-start.sh:delegated
            - ./dev-ssr.sh:/var/app/dev-ssr.sh:delegated
            - ./src:/var/app/src:delegated
        command: bash dev-start.sh
