version: "3"
services:
    hive_wallet:
        build: .
        image: hive/wallet:latest
        container_name: wallet
        ports:
            - 80:8080
            - 8080:8080
        environment:
            SDC_CLIENT_STEEMD_URL: https://api.hive.blog
            SDC_SERVER_STEEMD_URL: https://api.hive.blog
            SDC_DISABLE_SIGNUPS: 1
            SDC_SITE_DOMAIN: steemit.local
            SDC_IMAGE_PROXY_PREFIX: https://steemitimages.com/
            SDC_HELMET_CONNECTSRC: "'self' steemit.local https://api.hive.blog https://steemit.local http://steemit.local https://steemitimages.com"
            SDC_UPLOAD_IMAGE_URL: "https://steemitimages.com"
        volumes:
            - ./yarn.lock:/var/app/yarn.lock
            - ./package.json:/var/app/package.json
            - ./dev-start.sh:/var/app/dev-start.sh:delegated
            - ./dev-ssr.sh:/var/app/dev-ssr.sh:delegated
            - ./src:/var/app/src:delegated
        command: bash dev-start.sh
