version: "3"
services:
    wallet:
        image: hiveio/wallet:development
        deploy:
            mode: replicated
            replicas: 2
            resources:
                limits:
                    cpus: "0.85"
                    memory: 2024M
            restart_policy:
                condition: any
                delay: 5s
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
                order: start-first
            rollback_config:
                parallelism: 1
                delay: 5s
        environment:
            VIRTUAL_HOST: staging-wallet.hive.io
            VIRTUAL_PORT: 8080
            SDC_DATABASE_URL: mysql://root:mysecret@hive_mysql/hive_wallet
            SDC_CLIENT_HIVED_URL: https://anyx.io
            SDC_SERVER_HIVED_URL: https://anyx.io
            SDC_DISABLE_SIGNUPS: 1
            SDC_SITE_DOMAIN: staging-wallet.hive.io
            SDC_IMAGE_PROXY_PREFIX: https://images.hive.blog/
            SDC_UPLOAD_IMAGE_URL: https://images.hive.blog
            SDC_HELMET_CONNECTSRC: "'self' https://api.hive.blog https://anyx.io https://wallet.hive.blog https://images.hive.blog https://staging-wallet.hive.io"
            WALLET_URL: https://staging-wallet.hive.io
        networks:
            - reverse-proxy
            - database

    mysql:
        image: mysql:5.7
        container_name: hive_mysql
        volumes:
            - db_mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysecret
            MYSQL_DATABASE: hive_wallet
            MYSQL_USER: root
            MYSQL_PASSWORD: mysecret
        networks:
            - database

volumes:
    db_mysql:

networks:
    database:
    reverse-proxy:
        external: true
